OPENAI_API_KEY="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"
PERPLEXITY_API_BASE="https://api.perplexity.ai"
PERPLEXITY_API_KEY="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"
MISTRAL_API_KEY="XV00PMAZRzEFa7oZBKpbkE52oHDaOF1t"
ANYSCALE_API_KEY="esecret_qn7c1ny5mny2v9awaakm3jiqs2"